
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Tabla_simbolos_escenario {
  /* terminals */
  public static final int atributo_nombre = 22;
  public static final int r_extras = 13;
  public static final int r_meta = 16;
  public static final int r_heroes = 9;
  public static final int s_guion = 19;
  public static final int cerrar_p = 26;
  public static final int numero = 23;
  public static final int s_igual = 17;
  public static final int s_dospuntos = 24;
  public static final int r_suelo = 12;
  public static final int r_armas = 14;
  public static final int s_punto_coma = 18;
  public static final int r_paredes = 11;
  public static final int abrir_tag = 2;
  public static final int EOF = 0;
  public static final int abrir_p = 21;
  public static final int error = 1;
  public static final int r_fondo = 5;
  public static final int r_ancho = 6;
  public static final int r_personajes = 8;
  public static final int r_nombre = 4;
  public static final int s_coma = 25;
  public static final int r_alto = 7;
  public static final int r_escenario = 3;
  public static final int r_bonus = 15;
  public static final int r_villanos = 10;
  public static final int cerrar_tag = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "abrir_tag",
  "r_escenario",
  "r_nombre",
  "r_fondo",
  "r_ancho",
  "r_alto",
  "r_personajes",
  "r_heroes",
  "r_villanos",
  "r_paredes",
  "r_suelo",
  "r_extras",
  "r_armas",
  "r_bonus",
  "r_meta",
  "s_igual",
  "s_punto_coma",
  "s_guion",
  "cerrar_tag",
  "abrir_p",
  "atributo_nombre",
  "numero",
  "s_dospuntos",
  "s_coma",
  "cerrar_p"
  };
}

