
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Tabla_simbolos {
  /* terminals */
  public static final int atributo_nombre = 23;
  public static final int r_creditos = 8;
  public static final int r_bloque = 12;
  public static final int r_meta = 17;
  public static final int r_arma = 11;
  public static final int s_guion = 31;
  public static final int descripcion = 27;
  public static final int numero = 28;
  public static final int s_igual = 22;
  public static final int r_vida = 9;
  public static final int r_configuracion = 3;
  public static final int r_descripcion = 19;
  public static final int r_bomba = 13;
  public static final int r_imagen = 25;
  public static final int llave_abrir = 21;
  public static final int r_disenio = 5;
  public static final int r_destruir = 18;
  public static final int s_punto_coma = 24;
  public static final int s_comillas = 26;
  public static final int llave_cerrar = 30;
  public static final int r_enemigo = 15;
  public static final int abrir_tag = 2;
  public static final int EOF = 0;
  public static final int r_heroe = 16;
  public static final int error = 1;
  public static final int r_fondo = 4;
  public static final int r_tipo = 10;
  public static final int r_figura = 6;
  public static final int r_nombre = 7;
  public static final int s_coma = 29;
  public static final int r_bonus = 14;
  public static final int cerrar_tag = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "abrir_tag",
  "r_configuracion",
  "r_fondo",
  "r_disenio",
  "r_figura",
  "r_nombre",
  "r_creditos",
  "r_vida",
  "r_tipo",
  "r_arma",
  "r_bloque",
  "r_bomba",
  "r_bonus",
  "r_enemigo",
  "r_heroe",
  "r_meta",
  "r_destruir",
  "r_descripcion",
  "cerrar_tag",
  "llave_abrir",
  "s_igual",
  "atributo_nombre",
  "s_punto_coma",
  "r_imagen",
  "s_comillas",
  "descripcion",
  "numero",
  "s_coma",
  "llave_cerrar",
  "s_guion"
  };
}

