
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package Analizadores_escenario;

/** CUP generated class containing symbol constants. */
public class Tabla_simbolos_secuencia {
  /* terminals */
  public static final int r_nombre = 5;
  public static final int s_guion = 9;
  public static final int s_igual = 7;
  public static final int r_orden = 6;
  public static final int EOF = 0;
  public static final int r_escenario = 4;
  public static final int numero = 12;
  public static final int cerrar_tag = 10;
  public static final int error = 1;
  public static final int s_punto_coma = 8;
  public static final int abrir_tag = 2;
  public static final int atributo_nombre = 11;
  public static final int r_escenarios = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "abrir_tag",
  "r_escenarios",
  "r_escenario",
  "r_nombre",
  "r_orden",
  "s_igual",
  "s_punto_coma",
  "s_guion",
  "cerrar_tag",
  "atributo_nombre",
  "numero"
  };
}

