package UI;


import java.io.BufferedReader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Analizadores_configuracion.Lexico_configuracion;
import Analizadores_configuracion.Sintactico_configuracion;
import Analizadores.Lexico_escenario;
import Analizadores.Sintactico_escenario;

/**
 *
 * @author Cristian
 */
public class jFPrincipal extends javax.swing.JFrame {

    private Lexico_configuracion analizador_lexico;
    private Sintactico_configuracion analizador_sintactico;
    private Lexico_escenario analizador_lexico_escenarios;
    private Sintactico_escenario analizador_sintactico_escenarios;
    
    public jFPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEntrada = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMISalir = new javax.swing.JMenuItem();
        jMTabla_simbolos = new javax.swing.JMenu();
        jMICompilar_configuraciones = new javax.swing.JMenuItem();
        jMICompilar_escenarios = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMIErrores = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTAEntrada.setColumns(20);
        jTAEntrada.setRows(5);
        jScrollPane1.setViewportView(jTAEntrada);

        jMenu2.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nuevo");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Abrir");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guardar");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Guardar Como");
        jMenu2.add(jMenuItem4);

        jMISalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMISalir.setText("Salir");
        jMISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISalirActionPerformed(evt);
            }
        });
        jMenu2.add(jMISalir);

        jMenuBar1.add(jMenu2);

        jMTabla_simbolos.setText("Ejecutar");

        jMICompilar_configuraciones.setText("Compilar Archivo de Configuración");
        jMICompilar_configuraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICompilar_configuracionesActionPerformed(evt);
            }
        });
        jMTabla_simbolos.add(jMICompilar_configuraciones);

        jMICompilar_escenarios.setText("Compilar Archivo de Carga de Escenario");
        jMICompilar_escenarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICompilar_escenariosActionPerformed(evt);
            }
        });
        jMTabla_simbolos.add(jMICompilar_escenarios);

        jMenuItem8.setText("Compilar Archivo de secuencia de Escenarios");
        jMTabla_simbolos.add(jMenuItem8);

        jMenuItem9.setText("Ejecutar juego");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMTabla_simbolos.add(jMenuItem9);

        jMIErrores.setText("Errores");
        jMIErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIErroresActionPerformed(evt);
            }
        });
        jMTabla_simbolos.add(jMIErrores);

        jMenuItem11.setText("Tabla de Simbolos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMTabla_simbolos.add(jMenuItem11);

        jMenuBar1.add(jMTabla_simbolos);

        jMenu4.setText("Ayuda");

        jMenuItem12.setText("Manual de Usuario");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Manual Técnico");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Acerca de");
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMICompilar_configuracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICompilar_configuracionesActionPerformed
        try{
            String archivo_entrada = jTAEntrada.getText();
            if(!archivo_entrada.isEmpty()){
                analizador_lexico = new Lexico_configuracion(new BufferedReader(new StringReader(archivo_entrada)));
                analizador_sintactico = new Sintactico_configuracion(analizador_lexico);
                analizador_sintactico.parse();
            }else{
                JOptionPane.showMessageDialog(null,"NO HAY TEXTO PARA ANALIZAR","Precaución",JOptionPane.WARNING_MESSAGE);
            }
                       
        }catch(Exception ex){
             Logger.getLogger(jFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMICompilar_configuracionesActionPerformed

    private void jMISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMISalirActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jFTabla_simbolos ventana_tabla_simbolos = new jFTabla_simbolos();
        ventana_tabla_simbolos.show();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMIErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIErroresActionPerformed
        jFTabla_errores ventana_tabla_errores = new jFTabla_errores();
        ventana_tabla_errores.show();
    }//GEN-LAST:event_jMIErroresActionPerformed

    private void jMICompilar_escenariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICompilar_escenariosActionPerformed
        try{
            String archivo_entrada = jTAEntrada.getText();
            if(!archivo_entrada.isEmpty()){
                analizador_lexico_escenarios = new Lexico_escenario(new BufferedReader(new StringReader(archivo_entrada)));
                analizador_sintactico_escenarios = new Sintactico_escenario(analizador_lexico_escenarios);
                analizador_sintactico_escenarios.parse();
            }else{
                JOptionPane.showMessageDialog(null,"NO HAY TEXTO PARA ANALIZAR","Precaución",JOptionPane.WARNING_MESSAGE);
            }
                       
        }catch(Exception ex){
             Logger.getLogger(jFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMICompilar_escenariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMICompilar_configuraciones;
    private javax.swing.JMenuItem jMICompilar_escenarios;
    private javax.swing.JMenuItem jMIErrores;
    private javax.swing.JMenuItem jMISalir;
    private javax.swing.JMenu jMTabla_simbolos;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAEntrada;
    // End of variables declaration//GEN-END:variables
}
