package UI;

import Logica.Arbol_AST;
import Logica.Objeto;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cristian
 */
public class jFTabla_simbolos extends javax.swing.JFrame {
    
    private DefaultTableModel tabla_modelo;
    private String[] encabezado;
    private String[][] datos;
    private int filas;
    private final int columnas = 7;
    
    public jFTabla_simbolos() {
        initComponents();
        encabezado = new String[columnas];
        filas = Arbol_AST.getTabla_objetos().size();
        datos = new String[filas][columnas];
        setear_encabezados();
        setear_contenido();
        mostrar_datos();
    }
    
    public void setear_encabezados(){
        encabezado[0] = "Tipo";
        encabezado[1] = "Nombre";
        encabezado[2] = "Path Imagen";
        encabezado[3] = "Vida";
        encabezado[4] = "Destruir";
        encabezado[5] = "Bonus";
        encabezado[6] = "Descripcion";
    }//FIN DEL METODO QUE DA VALORES A LOS ENCABEZADOS

    public void setear_contenido(){
        int contx = 0;
        int conty = 0;
        for (Objeto value: Arbol_AST.getTabla_objetos().values()) {
            for(contx = 0; contx<7; contx++){
                switch(contx){
                    case 1:
                        datos[contx][conty] = value.getTipo();
                        break;
                    case 2:
                        datos[contx][conty] = value.getNombre();
                        break;
                    case 3:
                        datos[contx][conty] = value.getImagen();
                        break;
                    case 4:
                        datos[contx][conty] = Integer.toString(value.getVida());
                        break;
                    case 5:
                        datos[contx][conty] = Integer.toString(value.getDestruir());
                        break;
                    case 6:
                        datos[contx][conty] = value.getDescripcion();
                        break;
                }//fin del case para la posicion de las columnas
                        
            }//fin del contador de la posicion de las columnas

        }//fin del contador para poder recorrer toda la tabla hash
    }//fin del seteo de los datos
    
    public void mostrar_datos(){
        if(!Arbol_AST.getTabla_objetos().isEmpty()){
            tabla_modelo = new DefaultTableModel(datos,encabezado);
            jTabla_Simbolos.setModel(tabla_modelo);
        }else{
            tabla_modelo = new DefaultTableModel(datos,encabezado);
            jTabla_Simbolos.setModel(tabla_modelo);
        }
    }//fin del metodo para cargar la tabla en el jFrame 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTabla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla_Simbolos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPTabla.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("TABLA DE SIMBOLOS");

        jTabla_Simbolos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla_Simbolos);

        javax.swing.GroupLayout jPTablaLayout = new javax.swing.GroupLayout(jPTabla);
        jPTabla.setLayout(jPTablaLayout);
        jPTablaLayout.setHorizontalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(jPTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPTablaLayout.setVerticalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla_Simbolos;
    // End of variables declaration//GEN-END:variables
}
